### ISSUE TITLE
OkHTTP versions update

### ISSUE THREAD

**Issue by raver119** [Gitteroid/GitterJavaSDK#36]
It would be awesome if java sdk could be updated to okhttp/okhttp-ws version 2.7.5, as the most recent one. It's impossible right now, since okhttp api was slightly changed

**Comment by amatkivskiy** [comment]
@raver119 Thanks for reporting an issue. I will check the new version and make the update of the `OkHttp-WS`.

**Comment by amatkivskiy** [comment]
@raver119 Seems the latest OkHttp version is `3.5.0` with WebSockets in it.
I am planning update to this version. Or do you need especially 2.7.5 version?

**Comment by raver119** [comment]
No, any recent version would be awesome to have.
