### ISSUE TITLE
Can i send message to a user?

### ISSUE THREAD

**Issue by binglingziyu** [Gitteroid/GitterJavaSDK#41]

**Comment by amatkivskiy** [comment]
@binglingziyu Hi, it depends on whether you have already chatted with him or not.
- If yes, then you need just to get the room ID with him from user rooms and send a message to it.
`client.sendMessage("roomId", "message")`
- if no, then you need to [fetch the room ID](https://developer.gitter.im/docs/rooms-resource#join-a-room) for this user before sending message to him. Unfortunately this is not implemented at the moment in SDK but I will take a look on this and fix it.
Fetch ID request example: 
`curl -X POST -i -H "Content-Type: application/json" -H "Accept: application/json" -H "Authorization: Bearer {{token}}" "https://api.gitter.im/v1/rooms" -d '{"uri":"binglingziyu"}'`

**Comment by amatkivskiy** [comment]
@binglingziyu So I finally fixed this so you need to update to version 1.6.1.
So if you need to message a user and you've never had private room with him you need to :
- fetch room ID by making `RxGitterApiClient .getRoomIdByUri(user.username)` 
- get `room.id` from response and send message to it. `RxGitterApiClient.sendMessage(room.id, message)`

**Comment by amatkivskiy** [comment]
@binglingziyu I will close this issues for now. If you are still facing mentioned issue please contact me.
