### ISSUE TITLE
Android compatibility

### ISSUE THREAD

**Issue by terrysahaidak** [Gitteroid/GitterJavaSDK#7]
Hi. I'm working on my own android (react native) gitter client, I almost don't have experience with java, so I wanna ask: is your library (actually Faye part) i compatible with android?

**Comment by amatkivskiy** [comment]
@terrysahaidak Hi, yes it is.

**Comment by terrysahaidak** [comment]
Thank you :)

**Comment by amatkivskiy** [comment]
=)
